DROP TABLE IF EXISTS CITY;
DROP TABLE IF EXISTS HOTEL;
CREATE TABLE CITY(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, STATE
                   VARCHAR, COUNTRY VARCHAR);
CREATE TABLE HOTEL(CITY INT, NAME VARCHAR, ADDRESS VARCHAR, ZIP VARCHAR);