logging:
  level:
    root: INFO
server:
  port: 8081
management:
  security:
    enabled: false
spring:
  datasource:
    h2:
      master:
        url: jdbc:h2:mem:masterdb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
      slave:
        url: jdbc:h2:mem:slavedb
        driver-class-name: org.h2.Driver
        username: sa
        password: 